### ISSUE TITLE
Incorrect bits order

### ISSUE THREAD

**Issue by Mobivlad** [aasandroqq/SPL_Interrupt#1]
You have to send 4 MSB bits at first:
https://github.com/aasandroqq/SPL_Interrupt/blob/496bb66f4ecd9f8b086278f06de185ea48f7dc8e/SPL_IN/LCD.c#L38
And then 4 LSB bits:
https://github.com/aasandroqq/SPL_Interrupt/blob/496bb66f4ecd9f8b086278f06de185ea48f7dc8e/SPL_IN/LCD.c#L32

**Comment by aasandroqq** [comment]
Thanks for your commer
Fixed in new commit
